// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9PuzV5LUZOj0jk-B5jhTeJkIliHJej6s',
    appId: '1:1049276129941:web:17d40c980aad7a55fb319c',
    messagingSenderId: '1049276129941',
    projectId: 'blog-app-1a471',
    authDomain: 'blog-app-1a471.firebaseapp.com',
    storageBucket: 'blog-app-1a471.firebasestorage.app',
    measurementId: 'G-BNTGTREE2N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIzsY63oogu0fha7OoDKa4WaZQSODG3X4',
    appId: '1:1049276129941:android:dafc6cbb00f916d3fb319c',
    messagingSenderId: '1049276129941',
    projectId: 'blog-app-1a471',
    storageBucket: 'blog-app-1a471.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEllbQufOvyw3nM31ZEPPeQnz7KnElmq0',
    appId: '1:1049276129941:ios:7ab9c951ef3954d0fb319c',
    messagingSenderId: '1049276129941',
    projectId: 'blog-app-1a471',
    storageBucket: 'blog-app-1a471.firebasestorage.app',
    iosBundleId: 'com.example.blogApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEllbQufOvyw3nM31ZEPPeQnz7KnElmq0',
    appId: '1:1049276129941:ios:7ab9c951ef3954d0fb319c',
    messagingSenderId: '1049276129941',
    projectId: 'blog-app-1a471',
    storageBucket: 'blog-app-1a471.firebasestorage.app',
    iosBundleId: 'com.example.blogApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA9PuzV5LUZOj0jk-B5jhTeJkIliHJej6s',
    appId: '1:1049276129941:web:1d80ea8dd5a5cba2fb319c',
    messagingSenderId: '1049276129941',
    projectId: 'blog-app-1a471',
    authDomain: 'blog-app-1a471.firebaseapp.com',
    storageBucket: 'blog-app-1a471.firebasestorage.app',
    measurementId: 'G-Z5HBGR0DN3',
  );
}
